org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=D:\\xampp\\htdocs\\G2D\\safesoft_g2d_mobile\\android\\.tmp
org.gradle.vfs.watch=false
org.gradle.daemon=false
org.gradle.caching=false
org.gradle.parallel=false
org.gradle.workers.max=1
android.useAndroidX=true
android.enableJetifier=true
android.builder.sdkDownload=false
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false
